"""GitHub operations: clone repos, create branches, commit files, open PRs."""

import logging
import shutil
import uuid
from pathlib import Path

import git
from github import Github

import config

logger = logging.getLogger(__name__)

_gh = Github(config.GITHUB_TOKEN)


def get_bot_user():
    return _gh.get_user()


def clone_repo(repo_full_name: str, work_dir: Path) -> Path:
    """Clone a repository and return the local path."""
    clone_dir = work_dir / repo_full_name.replace("/", "_") / str(uuid.uuid4())[:8]
    clone_dir.parent.mkdir(parents=True, exist_ok=True)

    clone_url = f"https://x-access-token:{config.GITHUB_TOKEN}@github.com/{repo_full_name}.git"
    logger.info("Cloning %s to %s", repo_full_name, clone_dir)
    git.Repo.clone_from(clone_url, str(clone_dir), depth=1)
    return clone_dir


def get_file_tree(local_path: Path, max_depth: int = 4) -> str:
    """Get a compact file tree string for the repo."""
    lines = []

    def _walk(path: Path, prefix: str, depth: int):
        if depth > max_depth:
            return
        entries = sorted(path.iterdir(), key=lambda p: (p.is_file(), p.name))
        # Skip hidden dirs and common noise
        entries = [
            e for e in entries
            if not e.name.startswith(".")
            and e.name not in {"node_modules", "__pycache__", ".git", "venv", "env", "dist", "build"}
        ]
        for i, entry in enumerate(entries):
            connector = "└── " if i == len(entries) - 1 else "├── "
            lines.append(f"{prefix}{connector}{entry.name}")
            if entry.is_dir():
                extension = "    " if i == len(entries) - 1 else "│   "
                _walk(entry, prefix + extension, depth + 1)

    _walk(local_path, "", 0)
    return "\n".join(lines)


def read_priority_files(local_path: Path) -> dict[str, str]:
    """Read high-priority files (READMEs, build configs, etc.)."""
    results = {}
    for name in config.PRIORITY_FILES:
        fpath = local_path / name
        if fpath.is_file() and fpath.stat().st_size <= config.MAX_FILE_SIZE:
            try:
                results[name] = fpath.read_text(errors="replace")
            except Exception:
                pass
    return results


def read_code_files(local_path: Path, budget: int) -> dict[str, str]:
    """Read code files up to a budget count, prioritizing shorter files."""
    candidates = []
    for fpath in local_path.rglob("*"):
        if not fpath.is_file():
            continue
        if fpath.suffix not in config.CODE_EXTENSIONS:
            continue
        rel = fpath.relative_to(local_path)
        # Skip hidden/vendor paths
        parts = rel.parts
        if any(p.startswith(".") or p in {"node_modules", "__pycache__", "venv", "dist", "build"} for p in parts):
            continue
        size = fpath.stat().st_size
        if size > config.MAX_FILE_SIZE or size == 0:
            continue
        candidates.append((fpath, rel, size))

    # Sort by size ascending — smaller files first (headers, configs, entry points)
    candidates.sort(key=lambda x: x[2])

    results = {}
    for fpath, rel, _ in candidates[:budget]:
        try:
            results[str(rel)] = fpath.read_text(errors="replace")
        except Exception:
            pass
    return results


def create_branch_and_commit(
    local_path: Path,
    generated_files: dict[str, str],
    software_name: str,
) -> str:
    """Write generated files, commit on a new branch. Returns branch name."""
    repo = git.Repo(str(local_path))
    branch_name = f"cli-anything/{software_name}"

    repo.git.checkout("-b", branch_name)

    for rel_path, content in generated_files.items():
        fpath = local_path / rel_path
        fpath.parent.mkdir(parents=True, exist_ok=True)
        fpath.write_text(content)
        repo.index.add([rel_path])

    repo.index.commit(
        f"feat: add CLI-Anything harness for {software_name}\n\n"
        f"Auto-generated by cli-anything-bot following HARNESS.md methodology.\n"
        f"See the PR description for details on what was generated."
    )
    logger.info("Committed %d files on branch %s", len(generated_files), branch_name)
    return branch_name


def push_and_open_pr(
    repo_full_name: str,
    local_path: Path,
    branch_name: str,
    software_name: str,
    summary: str,
    issue_number: int | None = None,
) -> str:
    """Push branch and open a PR. Returns the PR URL."""
    repo = git.Repo(str(local_path))
    repo.git.push("origin", branch_name)

    gh_repo = _gh.get_repo(repo_full_name)
    default_branch = gh_repo.default_branch

    closes_line = f"\n\nCloses #{issue_number}" if issue_number else ""

    body = (
        f"## CLI-Anything Harness for `{software_name}`\n\n"
        f"{summary}\n\n"
        f"### What's included\n"
        f"- CLI entry point with Click commands and interactive REPL\n"
        f"- Core modules (project, session, export)\n"
        f"- Backend integration wrapper\n"
        f"- Unit tests and E2E test scaffolding\n"
        f"- `setup.py` for PyPI-ready packaging\n"
        f"- README with installation and usage instructions\n\n"
        f"### Generated by\n"
        f"[cli-anything-bot](https://github.com/anthropics/CLI-Anything/tree/main/bot) "
        f"using the [CLI-Anything](https://github.com/anthropics/CLI-Anything) methodology.{closes_line}\n"
    )

    pr = gh_repo.create_pull(
        title=f"feat: add CLI-Anything harness for {software_name}",
        body=body,
        head=branch_name,
        base=default_branch,
    )
    logger.info("Opened PR: %s", pr.html_url)
    return pr.html_url


def post_comment(repo_full_name: str, issue_number: int, body: str):
    """Post a comment on an issue or PR."""
    gh_repo = _gh.get_repo(repo_full_name)
    issue = gh_repo.get_issue(issue_number)
    issue.create_comment(body)


def add_reaction(repo_full_name: str, comment_id: int, reaction: str = "eyes"):
    """Add a reaction to a comment."""
    gh_repo = _gh.get_repo(repo_full_name)
    try:
        comment = gh_repo.get_issue_comment(comment_id)
        comment.create_reaction(reaction)
    except Exception:
        logger.debug("Could not add reaction to comment %d", comment_id)


def cleanup(local_path: Path):
    """Remove cloned repo directory."""
    try:
        shutil.rmtree(local_path)
    except Exception:
        logger.warning("Failed to clean up %s", local_path)
